const {test}=require('node:test'), assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os');
const {createApp}=require('../server'),{HASH,ROUTES}=require('../production/gates');
if(!process.env.GLEOR_FIXTURE_WORKSPACE){test('source-bound runtime fixtures',{skip:'Set GLEOR_FIXTURE_WORKSPACE to verified private fixture workspace'},()=>{});}else{
const root=fs.mkdtempSync(path.join(os.tmpdir(),'gleor-dry-')),workspace=process.env.GLEOR_FIXTURE_WORKSPACE,src=path.join(workspace,'output/source_authority_patch');
const read=f=>JSON.parse(fs.readFileSync(f)),results=[];
function save(d,n,b){fs.writeFileSync(path.join(d,n),b);return {path:n,sha256:HASH(b)};}
const rec=(d,n,o)=>save(d,n,Buffer.from(JSON.stringify(o)));
function setup(id,synthetic=false,retry=false){const d=path.join(root,id);fs.mkdirSync(d);const source=fs.readFileSync(path.join(src,'PRODUCT_TRUTH.png')),a=read(path.join(src,'IMG5684_SOURCE_SUFFICIENCY_FRONT_HERO.json')),locks={};for(const k of Object.keys(a.lock_hashes))locks[k]=save(d,k,fs.readFileSync(path.join(src,k)));
if(synthetic)for(const f of Object.values(a.features))if(f.state==='UNSUPPORTED_IDENTITY_CRITICAL')Object.assign(f,{state:'TRANSFORM_SUPPORTED',safe_constraint:'SYNTHETIC_TEST_ONLY',evidence:'SYNTHETIC_TEST_ONLY'});
const m={sku_id:synthetic?'SYNTHETIC':'IMG5684',category:'earring',target_view:'FRONT_HERO',micro_applicable:true,finish_id:'gleor_champagne_rose_v1',finish_revision:'1.2.0',product_truth:{id:'IMG5684',...save(d,'source.png',source)},locks,assessment:rec(d,'assessment.json',a),internal_only_renderer:true,allow_controlled_retry:retry,prerequisites:{}};
for(const k of ['STRUCTURE_CHECK','MACRO_PRODUCT_TRUTH_INSPECTION','EXISTING_VIEW_DETECTION','IDENTIFY_MISSING_VIEW','CLOSURE_LOCK','FRONT_CAMERA_LOCK','MICRO_SETTING_INSPECTION'])m.prerequisites[k]={status:'PASS',source_sha256:HASH(source),evidence_ref:'SYNTHETIC_ONLY'};
m.finish_reference=save(d,'finish-reference.png',fs.readFileSync(path.join(workspace,'inputs/Minimalist Rose Altın Halka Küpeler.png')));
rec(d,'manifest.json',m);rec(d,'attempt-ledger.json',{attempts:0});return d;}
const pass=b=>({status:'PASS',asset_sha256:HASH(b),evidence_ref:'SYNTHETIC_ONLY'});
function adapters(fail){return {render:async()=>Buffer.from('SYNTHETIC_INTERNAL'),macro:async b=>pass(b),micro:async b=>({...pass(b),status:fail==='micro'?'FAIL':'PASS'}),viewAware:async b=>pass(b),closure:async b=>pass(b),camera:async b=>pass(b),metalMap:async b=>pass(b),finish:async ({image})=>({image}),verifyAppearance:async ({after})=>({...pass(after),status:fail==='geometry'?'FAIL':'PASS'}),finishQA:async b=>({...pass(b),status:fail==='finish'?'FAIL':'PASS'}),gateM:async b=>pass(b),gateF:async b=>pass(b),markings:async b=>b,framing:async ({image})=>({image,height:408}),pair:async image=>({image,alignment:'PASS'}),premium:async b=>pass(b)};}
async function request(route,id,ops={}){const app=createApp({root,dryRun:true,...ops}),server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{const r=await fetch(`http://127.0.0.1:${server.address().port}${route}`,{method:'POST',headers:{'Content-Type':'application/json','X-Gleor-Run-Id':id,'X-Catalog-Include-Artifacts':'1'},body:JSON.stringify({SOURCE_SUFFICIENCY:'PASS',RELEASE_GATE:'PASS',category:'ring'})});return {code:r.status,body:await r.json()};}finally{await new Promise(r=>server.close(r));}}
test('A/E IMG5684 zero calls through all actual routes despite forged PASS',async()=>{for(const [i,route]of ROUTES.entries()){const id='negative'+i;setup(id);const r=await request(route,id,{adapters:adapters()});assert.equal(r.code,409);assert.equal(r.body.reason,'INSUFFICIENT_PRODUCT_TRUTH_FOR_FRONT_HERO');assert.equal(r.body.state.RECONSTRUCTION_AUTHORIZATION,'DENIED');assert.equal(r.body.state.RENDER_PROVIDER_CALL_COUNT,0);assert.deepEqual(r.body.state.calls,{});assert.equal(r.body.image,undefined);assert.equal(read(path.join(root,id,'attempt-ledger.json')).attempts,0);assert.deepEqual(r.body.missing_evidence,['UPPER_HOLDER_FRONT_CONTOUR_AND_CONTACT_INTERFACE','LOWER_HOLDER_FRONT_TOPOLOGY_AND_RAIL_CONNECTION']);}results.push({test:'A/E',status:'PASS',routes:ROUTES,provider_calls:0,retries:0});});
test('C/D structural, finish and geometry failures block downstream on every route',async()=>{for(const fail of ['micro','finish','geometry'])for(const [i,route]of ROUTES.entries()){const id=fail+i;setup(id,true);const r=await request(route,id,{adapters:adapters(fail)});assert.equal(r.code,409);assert.equal(r.body.image,undefined);assert.equal(r.body.state.RELEASE_GATE_STATUS,'BLOCKED');for(const k of fail==='micro'?['finish','pair','premium']:['pair','premium'])assert.equal(r.body.state.calls[k],undefined);assert.equal(r.body.state.calls.render,1);}results.push({test:'C/D',status:'PASS',scope:'real HTTP routes, synthetic trusted adapters only'});});
test('B IMG5751 exact accepted export replay through shared release gate, unchanged original',async()=>{const d=path.join(root,'accepted');fs.mkdirSync(d);const base=path.join(workspace,'inputs/standard'),known=read(path.join(base,'IMG5751_CANONICAL_EXAMPLE.json'));const original=known.assets.final_export.path,before=fs.readFileSync(original);assert.equal(HASH(before),known.assets.final_export.sha256);const raw=fs.readFileSync(known.assets.product_truth.path);
rec(d,'manifest.json',{sku_id:'IMG5751',category:'earring',target_view:'EXISTING_ACCEPTED_PAIR',mode:'ACCEPTED_EXPORT_REPLAY',finish_id:'gleor_champagne_rose_v1',finish_revision:'1.2.0',product_truth:{id:'IMG5751',...save(d,'source.png',raw)},final_asset:save(d,'accepted.png',before),acceptance_record:save(d,'accepted.json',fs.readFileSync(path.join(base,'canonical_provenance/IMG5751_FINAL_EXPORT/FINAL_EXPORT_RECORD.json'))),premium_record:save(d,'premium.json',fs.readFileSync(path.join(base,'canonical_provenance/IMG5751_FINAL_PREMIUM_QA/PREMIUM_QA.json')))});
for(const route of ROUTES){const r=await request(route,'accepted');assert.equal(r.code,200);assert.equal(r.body.state.RELEASE_GATE_STATUS,'PASS');assert.equal(HASH(Buffer.from(r.body.image,'base64')),HASH(before));}assert.ok(fs.readFileSync(original).equals(before));results.push({test:'B',status:'PASS',sha256:HASH(before),scope:'accepted byte-identical export replay; no retroactive structural recertification'});});
test('fail closed unknown run, missing adapters, corrupted source, unknown/crashed gate, exhausted retry',async()=>{for(const route of ROUTES){const r=await request(route,'unknown');assert.equal(r.code,409);assert.equal(r.body.image,undefined);}setup('noAdapters',true);assert.equal((await request('/catalog','noAdapters')).code,409);const d=setup('corrupt',true);fs.appendFileSync(path.join(d,'source.png'),'bad');const bad=await request('/catalog','corrupt',{adapters:adapters()});assert.equal(bad.body.reason,'EVIDENCE_HASH_MISMATCH');assert.deepEqual(bad.body.state.calls,{});
for(const mode of ['unknownGate','crash']){setup(mode,true,true);const a=adapters();a.micro=async b=>{if(mode==='crash')throw Error('synthetic');return {...pass(b),status:'UNKNOWN'};};const r=await request('/catalog',mode,{adapters:a});assert.equal(r.code,409);assert.equal(r.body.state.calls.render,1);assert.equal(r.body.state.calls.finish,undefined);}
setup('budget',true,true);const r=await request('/catalog','budget',{adapters:adapters('micro')});assert.equal(r.body.state.calls.render,2);const r2=await request('/hero','budget',{adapters:adapters()});assert.equal(r2.body.reason,'RETRY_EXHAUSTED');assert.equal(r2.body.state.calls.render,undefined);results.push({test:'fail_closed',status:'PASS'});fs.writeFileSync(path.join(__dirname,'../production/TEST_RESULTS.json'),JSON.stringify({results,live_deployed:false,real_provider_calls:0,synthetic_adapters_are_not_production_QA:true},null,2));});

}
